export const FETCH_ALL_CUSTOMER_PENDING = "FETCH_ALL_CUSTOMER_PENDING";
export const FETCH_ALL_CUSTOMER_SUCCESS = "FETCH_ALL_CUSTOMER_SUCCESS";
export const FETCH_ALL_CUSTOMER_FAILED = "FETCH_ALL_CUSTOMER_FAILED";

export const FETCH_ONE_CUSTOMER_PENDING = "FETCH_ONE_CUSTOMER_PENDING";
export const FETCH_ONE_CUSTOMER_SUCCESS = "FETCH_ONE_CUSTOMER_SUCCESS";
export const FETCH_ONE_CUSTOMER_FAILED = "FETCH_ONE_CUSTOMER_FAILED";

export const ADD_CUSTOMER_PENDING = "ADD_CUSTOMER_PENDING";
export const ADD_CUSTOMER_SUCCESS = "ADD_CUSTOMER_SUCCESS";
export const ADD_CUSTOMER_FAILED = "ADD_CUSTOMER_FAILED";

export const REMOVE_CUSTOMER_PENDING = "REMOVE_CUSTOMER_PENDING";
export const REMOVE_CUSTOMER_SUCCESS = "REMOVE_CUSTOMER_SUCCESS";
export const REMOVE_CUSTOMER_FAILED = "REMOVE_CUSTOMER_FAILED";

export const BASE_URL = `http://localhost:8001/customers/`;
