export const FETCH_ALL_TEE_TIMES = "FETCH_ALL_TEE_TIMES";
export const FETCH_ALL_TEE_TIMES_SUCCESS = "FETCH_ALL_TEE_TIMES_SUCCESS";
export const FETCH_ALL_TEE_TIMES_FAILED = "FETCH_ALL_TEE_TIMES_FAILED";
export const FETCH_ALL_TEE_TIMES_PENDING = "FETCH_ALL_TEE_TIMES_PENDING";

export const FETCH_ONE_TEE_TIMES = "FETCH_ONE_TEE_TIMES";
export const FETCH_ONE_TEE_TIMES_SUCCESS = "FETCH_ONE_TEE_TIMES_SUCCESS";
export const FETCH_ONE_TEE_TIMES_FAILED = "FETCH_ONE_TEE_TIMES_FAILED";
export const FETCH_ONE_TEE_TIMES_PENDING = "FETCH_ONE_TEE_TIMES_PENDING";

export const ADD_TEE_TIMES = "ADD_TEE_TIMES";
export const ADD_TEE_TIMES_SUCCESS = "ADD_TEE_TIMES_SUCCESS";
export const ADD_TEE_TIMES_FAILED = "ADD_TEE_TIMES_FAILED";
export const ADD_TEE_TIMES_PENDING = "ADD_TEE_TIMES_PENDING";

export const REMOVE_TEE_TIMES = "REMOVE_TEE_TIMES";
export const REMOVE_TEE_TIMES_SUCCESS = "REMOVE_TEE_TIMES_SUCCESS";
export const REMOVE_TEE_TIMES_FAILED = "REMOVE_TEE_TIMES_FAILED";
export const REMOVE_TEE_TIMES_PENDING = "REMOVE_TEE_TIMES_PENDING";

export const BASE_URL = `http://localhost:8001/tee_times/`;
